In [45]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

In [46]:
df = pd.read_csv('dataset_panjang_v2.csv')
df

waktu        step   panjang
0         6    4.375691  0.380893
1        11    8.022099  0.380893
2        16   11.668508  0.380893
3        21   15.314917  0.380893
4        26   18.961326  0.380893
...     ...         ...       ...
1040    143  377.442177  1.262888
1041    144  380.081633  1.262888
1042    145  382.721088  1.262888
1043    146  385.360544  1.262888
1044    147  388.000000  1.262888

[1045 rows x 3 columns]

In [47]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('panjang',axis='columns'),df.panjang)

LinearRegression()

In [48]:
reg.coef_

array([-0.00307786,  0.00143617])

In [49]:
reg.intercept_

0.8343048305325581

In [50]:
reg.predict([[6, 4]])

array([0.82158236])

In [51]:
poly = PolynomialFeatures(degree = 4)
X_poly = poly.fit_transform(df.drop('panjang',axis='columns'))

In [52]:
poly.fit(X_poly, df.panjang)
lin2 = linear_model.LinearRegression()
lin2.fit(X_poly, df.panjang)

LinearRegression()

In [73]:
# Predicting a new result with Polynomial Regression after converting predict variable to 2D array
pred2 = 86
pred21 = 220
pred2array = np.array([[pred2, pred21]])
panjang = lin2.predict(poly.fit_transform(pred2array))
panjang

array([1.03732521])

In [55]:
lin2.coef_

array([ 0.00000000e+00, -2.62162386e-02,  1.41720038e-02,  3.79763487e-04,
       -2.77353599e-04,  3.07314972e-05, -5.86866902e-06,  9.33666781e-06,
       -4.96852246e-06,  8.99248461e-07,  3.31665615e-08, -7.07633745e-08,
        5.43784605e-08, -1.78470295e-08,  2.10111075e-09])

In [65]:
lin2.intercept_

0.8154092693662105